/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import static test.fileWriter.br;

/**
 *
 * @author Marcel Marais
 */
public class LoginGUI extends javax.swing.JFrame {

    String clickSound = "Music/Click.wav";
    GameFrame f = new GameFrame ();
    static boolean prevUser;
    boolean ready = false;
    GenerateUserAccount a = new GenerateUserAccount ();
    static String password;
    public static String name;
    public static int index;
    boolean save = false;
    fileReader fr = new fileReader ();

    boolean correct = false;
    boolean done = false;

    Toolkit tk = Toolkit.getDefaultToolkit ();
    static String file = "Data/UsersWithScore.txt";

    int x = (int) tk.getScreenSize ().getWidth ();
    int y = (int) tk.getScreenSize ().getHeight ();

    /**
     * Creates new form loginGUI
     */
    public LoginGUI () {

        initComponents ();
        MainHeadingLabel.setLocation ((1024 - MainHeadingLabel.getWidth ()) / 2, 40);//Centers TITLE
        String a = NameTxtBox.getText ();

        jLabel7.setVisible (false);
        jLabel8.setVisible (false);

        jLabel2.setVisible (false);
        jLabel2.setLocation ((1024 - jLabel2.getWidth ()) / 2, 160 + 50);

        jLabel4.setVisible (false);
        jLabel4.setLocation ((1024 - jLabel4.getWidth ()) / 2, 160 + 150);//pass str

        jLabel5.setVisible (false);
        jLabel5.setLocation ((1024 - jLabel5.getWidth ()) / 2, 160 + 50);//Username

        jLabel6.setVisible (false);
        jLabel6.setLocation ((1024 - jLabel6.getWidth ()) / 2, 160 + 150 + 50);//password

        SignUpButton.setLocation ((1024 - SignUpButton.getWidth ()) / 2, 210);//Signup
        LoginButton.setLocation ((1024 - LoginButton.getWidth ()) / 2, 310);//Login

        NameTxtBox.setVisible (false);//Enter name
        NameTxtBox.setSize (jLabel2.getWidth () - 30, 30);
        NameTxtBox.setLocation ((1024 - NameTxtBox.getWidth ()) / 2, 210 + 50);

        PasswordStrengthTxtBox.setVisible (false);//Enter pass
        PasswordStrengthTxtBox.setSize (jLabel2.getWidth () - 30, 30);
        PasswordStrengthTxtBox.setLocation ((1024 - PasswordStrengthTxtBox.getWidth ()) / 2, 160 + 150 + 45);

        jButton3.setVisible (false);//Start game
        jButton3.setLocation ((1024 - jButton3.getWidth ()) / 2, 260 + 150 + 75 + 20);

        GenerateUserButton.setVisible (false);//Generate user
        GenerateUserButton.setLocation ((1024 - GenerateUserButton.getWidth ()) / 2, 260 + 150 + 20);

        jButton4.setLocation ((1024 - jButton4.getWidth ()), (700 - (jButton4.getHeight () + 3)));//exit

        StartGameButton.setVisible (false);
        PasswordTxtBox.setVisible (false);
        UsernameTxtBox.setVisible (false);

        setAlwaysOnTop (true);
        setSize (1024, 700);
        setLocation ((x - this.getWidth ()) / 2, ((y - this.getHeight ()) / 2));
        //setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NameTxtBox = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        MainHeadingLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PasswordStrengthTxtBox = new javax.swing.JTextField();
        GenerateUserButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PasswordTxtBox = new javax.swing.JTextField();
        UsernameTxtBox = new javax.swing.JTextField();
        StartGameButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        SignUpButton.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        SignUpButton.setText("Sign up");
        SignUpButton.setToolTipText("Click here to sign up!");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpButton);
        SignUpButton.setBounds(600, 250, 250, 70);

        LoginButton.setBackground(java.awt.Color.lightGray);
        LoginButton.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setToolTipText("Click here to login!");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(600, 180, 250, 70);

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter your name:");
        jLabel2.setToolTipText("No numbers allowed");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 180, 370, 60);

        NameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtBoxActionPerformed(evt);
            }
        });
        getContentPane().add(NameTxtBox);
        NameTxtBox.setBounds(226, 252, 204, 26);

        jButton3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jButton3.setText("Begin game!\n");
        jButton3.setToolTipText("Click here to begin your first round!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(70, 590, 160, 40);

        MainHeadingLabel.setFont(new java.awt.Font("Luminari", 0, 80)); // NOI18N
        MainHeadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainHeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainHeadingLabel.setText("Welcome to Axe Run!");
        getContentPane().add(MainHeadingLabel);
        MainHeadingLabel.setBounds(130, 40, 925, 120);

        jButton4.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.setToolTipText("Click here to close the game");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(930, 670, 97, 29);

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter password strength (1-10):");
        jLabel4.setToolTipText("Hint: must be a number from 1-10");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 660, 50);

        PasswordStrengthTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordStrengthTxtBoxActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordStrengthTxtBox);
        PasswordStrengthTxtBox.setBounds(220, 360, 240, 26);

        GenerateUserButton.setText("Generate user");
        GenerateUserButton.setToolTipText("Click here to generate your login details");
        GenerateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateUserButton);
        GenerateUserButton.setBounds(250, 400, 180, 29);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Username:");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 520, 250, 60);

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password:");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 450, 250, 60);

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("uN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 480, 220, 60);

        jLabel8.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pass");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 540, 360, 60);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(900, 380, 45, 16);

        PasswordTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtBoxActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordTxtBox);
        PasswordTxtBox.setBounds(520, 480, 180, 30);

        UsernameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTxtBoxActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTxtBox);
        UsernameTxtBox.setBounds(520, 440, 180, 30);

        StartGameButton.setText("Start game!");
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StartGameButton);
        StartGameButton.setBounds(550, 520, 110, 29);

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/backg.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 2300, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        MusicPlayer.playMusic (clickSound);
        PasswordStrengthTxtBox.setVisible (true);
        NameTxtBox.setVisible (true);
        jLabel4.setVisible (true);
        GenerateUserButton.setVisible (true);

        MainHeadingLabel.setText ("Welcome new user!");
        jLabel2.setVisible (true);
        SignUpButton.setVisible (false);
        LoginButton.setVisible (false);    // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonActionPerformed

    /**
     * Button the sets the name of the user
     *
     * @param name
     */
    public void setName (String name) {
        jLabel7.setText (name);
    }

    /**
     * Button that sets the password for the user
     *
     * @param pass
     */
    public void setPass (String pass) {
        jLabel8.setText (pass);
    }

    private void NameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MusicPlayer.playMusic (clickSound);
        Main.next ();
        dispose ();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MusicPlayer.playMusic (clickSound);
        System.exit (0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Button that moves user onto the sign in screen
     *
     * @param evt
     */
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        MusicPlayer.playMusic (clickSound);
        MainHeadingLabel.setText ("Welcome Back!");
        jLabel4.setText ("Password:");
        PasswordTxtBox.setSize (jLabel2.getWidth () - 30, 30);
        PasswordTxtBox.setLocation ((1024 - NameTxtBox.getWidth ()) / 2, 210 + 50);
        UsernameTxtBox.setSize (jLabel2.getWidth () - 30, 30);
        UsernameTxtBox.setLocation ((1024 - PasswordStrengthTxtBox.getWidth ()) / 2, 160 + 150 + 45);
        StartGameButton.setLocation ((1024 - jButton3.getWidth ()) / 2, 260 + 150);

        SignUpButton.setVisible (false);
        LoginButton.setVisible (false);

        PasswordTxtBox.setVisible (true);
        UsernameTxtBox.setVisible (true);
        MainHeadingLabel.setVisible (true);
        jLabel2.setVisible (true);
        jLabel4.setVisible (true);
        StartGameButton.setVisible (true);

// TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void PasswordStrengthTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordStrengthTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordStrengthTxtBoxActionPerformed

    /**
     * Button that Validates user data when pressed
     *
     * @param evt
     */
    private void GenerateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateUserButtonActionPerformed
        MusicPlayer.playMusic (clickSound);
        correct = false;
//        try {
//            int i = 0;
//
//            br = new BufferedReader (new FileReader (file));
//            String line = br.readLine ();
//            while (line != null) {
//                System.out.println (i);
//
//                fileReader.content ()[i].setScore (Integer.parseInt (line.split ("#")[2]));
//                System.out.println (line);
//                System.out.println (fileReader.content ()[i].getName ());
//                line = br.readLine ();
//                i++;
//            }
//        } catch (Exception e) {
//            e.printStackTrace ();
//        }
        boolean right = false;

        int s = Integer.parseInt (PasswordStrengthTxtBox.getText ());
        if (s > 10 || s < 0) {
            MainHeadingLabel.setText ("Please enter a valid value");
            right = false;
        }
        if (s > 0 && s <= 10) {
            right = true;
        }

        password = a.getPass (s, NameTxtBox.getText ());
        name = a.getUserName (NameTxtBox.getText ());

        int i = 0;
        int str = 0;
        int finished = 0;

        if (correct == false && s <= 10 && s > 0) {

            MainHeadingLabel.setText ("Invalid Input");
            try {

                str = s;

                if (str < 10 && str > 0 && correct == false) {
                    correct = true;
                } else {
                    correct = false;
                    s = Integer.parseInt (PasswordStrengthTxtBox.getText ());
                }

            } catch (NumberFormatException d) {
                i += 1;
                correct = false;

            }
        }

        if (i == 5) {
            jLabel6.setText ("Please enter a number");
        }

        done = false;

        CharSequence notIn1 = "1";
        CharSequence notIn2 = "2";
        CharSequence notIn3 = "3";
        CharSequence notIn4 = "4";
        CharSequence notIn5 = "5";
        CharSequence notIn6 = "6";
        CharSequence notIn7 = "7";
        CharSequence notIn8 = "8";
        CharSequence notIn9 = "9";
        CharSequence notIn0 = "0";

        boolean check = true;

        if (done == false) {
            try {

                for (int a = 0; a < name.length (); a++) {
                    boolean IsNumber1 = name.contains (notIn1);
                    boolean IsNumber2 = name.contains (notIn2);
                    boolean IsNumber3 = name.contains (notIn3);
                    boolean IsNumber4 = name.contains (notIn4);
                    boolean IsNumber5 = name.contains (notIn5);
                    boolean IsNumber6 = name.contains (notIn6);
                    boolean IsNumber7 = name.contains (notIn7);
                    boolean IsNumber8 = name.contains (notIn8);
                    boolean IsNumber9 = name.contains (notIn9);
                    boolean IsNumber0 = name.contains (notIn0);

                    done = true;

                    if (name.contains (notIn2) || name.contains (notIn3) || name.contains (notIn4) || name.contains (notIn5) || name.contains (notIn6) || name.contains (notIn7) || name.contains (notIn8) || name.contains (notIn9) || name.contains (notIn0) || name.contains (notIn1)) {
                        done = false;
                    }
                }

            } catch (StringIndexOutOfBoundsException e) {
                System.out.println ("Please Enter a name");
                done = false;
            }

        }

        if (correct = true && done == true && right == true) {
            jButton4.setVisible (false);
            Main.save ();
            save = true;
            jLabel7.setText (name);
            jLabel8.setText (password);

            jLabel7.setLocation ((1024 - jLabel7.getWidth ()) / 2, 160 + 50 + 63);
            jLabel8.setLocation ((1024 - jLabel8.getWidth ()) / 2, 160 + 150 + 50 + 63);

            jLabel7.setVisible (true);
            jLabel8.setVisible (true);
            jLabel5.setVisible (true);
            jLabel6.setVisible (true);
            jButton3.setVisible (true);
            MainHeadingLabel.setText ("Welcome " + NameTxtBox.getText () + "!");

            PasswordStrengthTxtBox.setVisible (false);
            NameTxtBox.setVisible (false);
            jLabel2.setVisible (false);

            jLabel4.setVisible (false);
            GenerateUserButton.setVisible (false);

        }
    }//GEN-LAST:event_GenerateUserButtonActionPerformed

    private void PasswordTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTxtBoxActionPerformed

    private void UsernameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTxtBoxActionPerformed

    public static boolean getPrevUser () {
        return prevUser;
    }

    /**
     * Button that checks if user data matches what is in the text file
     *
     * @param evt
     */
    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        MusicPlayer.playMusic (clickSound);
        String usr = PasswordTxtBox.getText ();
        String pass = UsernameTxtBox.getText ();
        String s = "";
        int checker = 0;
        int len = 0;

        try {
            int i = 0;

            br = new BufferedReader (new FileReader (file));
            String line = br.readLine ();
            while (line != null) {
                fileReader.content ()[i].setScore (Integer.parseInt (line.split ("#")[2]));
                System.out.println (fileReader.content ()[i].getScore ());
                line = br.readLine ();
                i++;
                len = i;
                prevUser = true;
            }
        } catch (Exception e) {
            e.printStackTrace ();
        }
        try {
            // fileReader.readStuff (true);
            UserData dt[] = fileReader.content ();
            while (checker < len) {
                s = dt[checker].getPass ();
                if (s.equals (pass)) {
                    Character.setHealth (10);
                    Main.next ();
                    index = checker;
                    dispose ();
                } else {
                    MainHeadingLabel.setText ("Incorrect Credentials");
                }

                checker++;
            }

        } catch (NullPointerException e) {
            System.out.println ("No username");
            MainHeadingLabel.setText ("Incorrect Credentials");
        }
    }//GEN-LAST:event_StartGameButtonActionPerformed

    /**
     * Checks if data has been saved
     *
     * @return If saved
     */
    public boolean getSave () {
        return save;
    }

    /**
     * Returns the password that the user has inputted
     *
     * @return
     */
    public String getPass () {
        return password;
    }

    /**
     * Returns the username the user has entered
     *
     * @return
     */
    public String getUsername () {
        return name;
    }

    public static int getIndex () {
        return index;
    }

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ()) {
                if ("Nimbus".equals (info.getName ())) {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger (LoginGUI.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger (LoginGUI.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger (LoginGUI.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger (LoginGUI.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable () {
            public void run () {
                new LoginGUI ().setVisible (true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateUserButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel MainHeadingLabel;
    private javax.swing.JTextField NameTxtBox;
    private javax.swing.JTextField PasswordStrengthTxtBox;
    private javax.swing.JTextField PasswordTxtBox;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JTextField UsernameTxtBox;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
